development:
  adapter: postgresql
  encoding: unicode
  database: teamlog_development
  host: "127.0.0.1"
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: teamlog_test
  host: "127.0.0.1"
  pool: 5
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: teamlog_production
  host: "127.0.0.1"
  pool: 5
